# Generated by Django 5.2.8 on 2025-11-16 09:18

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=64)),
                ('id_photo', cloudinary.models.CloudinaryField(max_length=255)),
                ('id_verified', models.BooleanField(default=False)),
                ('vehicle_type', models.CharField(choices=[('car', 'Car'), ('van', 'Van'), ('matatu', 'Matatu'), ('motorbike', 'Motorbike')], max_length=32)),
                ('vehicle_seats', models.PositiveIntegerField(default=4)),
                ('location', models.CharField(help_text='City/neighborhood', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=32)),
                ('is_active_searchable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
