# Generated by Django 5.2.8 on 2026-04-10 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverprofile',
            name='location',
            field=models.CharField(help_text='Driver base city/neighborhood', max_length=255),
        ),
        migrations.CreateModel(
            name='DriverDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='drivers.driverprofile')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('driver', 'name')},
            },
        ),
    ]
